version: '3'
services:
  nodejs-app:
    image: node:16
    working_dir: /app
    volumes:
       - ./:/app
    ports:
       - "3000:3000"
    environment:
       NODE_ENV: production
    command: npm start

  mongodb:
    image: mongo
    environment:
       MONGO_INITDB_ROOT_USERNAME: jay
       MONGO_INITDB_ROOT_PASSWORD: ClPTaJtE9IEVFBis
       MONGO_INITDB_DATABASE: Cluster1
    ports:
       - "27017:27017"

